version: '2'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-reverseproxy
    ports:
      - 80:80
    volumes:
      - ./nginx-reverseproxy.conf:/etc/nginx/conf.d/default.conf
    network_mode: host
